#!/bin/bash

set -ex

# this script is executed after our rails images default assemble script.

pushd /opt/app-root/src

echo "DEMO_INSTANCE is set to: $DEMO_INSTANCE"
# load development seeds when demo instance
if [ $DEMO_INSTANCE -eq 1 ]; then
  echo 'demo instance: creating symlink for loading development seeds'
  for wagon in vendor/wagons/*
  do
    cd $wagon/db/seeds
    ln -s development production
  done
fi

# TODO pull transifex translations

popd


